/**
 * @description       :
 * @author            : Prateek Deshmukh
 * @group             : Prateek Deshmukh,Aditya S,Mahalakshmi
 * @last modified on  : 06-04-2024
 * @last modified by  : Prateek Deshmukh
**/
public class HelloWorld {
    
    /**
     * @description Bar
     *
     */
    public static void sayHello() {
        // Use LoggingLevel to categorize the debug statement
        integer i = 5;
        if (i == 5) {
            i++;
        }  
    }
}
