name: Deploying the changes to the Production
run-name: ${{ github.actor }} is running the Github Actions 🚀

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - 'force-app/**'

jobs:
  build-and-deploy: 
    name: Deploying the changes to Production 
    uses: "./.github/workflows/template-Production.yml"
    permissions:
      contents: read
      security-events: write
      actions: read
    with:
      environment: Production
    secrets: inherit