name: Validate to Production Org
run-name: ${{ github.actor }} is running the Github Actions 🚀

on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    branches:
      - main
    paths:
      - 'force-app/**'

jobs:
  build-and-deploy: 
    name: Validating the changes against Production environment
    uses: "./.github/workflows/template-Production.yml"
    permissions:
      contents: read
      security-events: write
      actions: read
    with:
      environment: Production
    secrets: inherit